name: gymshare
description: Gymshare mobile application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.3.0
  google_fonts: ^3.0.1
  email_validator: ^2.1.17
  http: ^0.13.5
  shared_preferences: ^2.0.15
  flutter_svg: ^1.1.5
  curved_navigation_bar: ^1.0.3
  jwt_decoder: ^2.0.1
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.55.2
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  flutter_time_picker_spinner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/logo.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/logo_foreground.png'

flutter:
  uses-material-design: true

  assets:
    - assets/
